on:
  push:
    branches:
      - main

name: 🚀 Deploy app on push

jobs:
  install-build-and-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clear npm cache
        run: npm cache clean --force

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Adjust to your preferred Node.js version

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: ./

      - name: Debug Directory
        run: |
          pwd
          ls -l

      - name: Navigate to scholar_app directory
        run: |
          cd scholar_app/scholar_app
          ls

      - name: Install project dependencies with npm
        run: |
          cd /home/runner/work/bug_vcsch_2023/bug_vcsch_2023/scholar_app
          npm install --prefix ./scholar_app

      - name: Build the Next.js app
        run: |
          cd /home/runner/work/bug_vcsch_2023/bug_vcsch_2023/scholar_app
          npm run build --prefix ./scholar_app

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.vcscholar.org
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: ./
